Added Row and Column in Layout
DioxusLabs/components pull request #2
Opened 2024-04-10 02:17 UTC by wheregmis

2024-04-11 04:20 UTC, wheregmis commented
@DogeDark example works with include_str but doesnt work with manganis. I also saw an issue on collect asset repository. I will wait for it to be closed for this pr to make it work with manganis, or feel free to merge or review.

2024-04-11 23:48 UTC, DogeDark requested changes
Looks pretty good! Just a few things.

2024-04-11 23:48 UTC, DogeDark commented on components/src/layout/column.rs
> +            style: "dxc-column",
I believe this should be ``class``

2024-04-11 23:48 UTC, DogeDark commented on components/src/layout/column.rs
> +        // style { {include_str!("../../css-out/column.css")} }
You can remove the ``style``s and ``include_str``s. At the moment I'm not worried about the assets not working for examples.

2024-04-11 23:48 UTC, DogeDark commented on examples/preview/src/main.rs
> +            class: "bg-gray-100 p-5",
Looks like some Tailwind got through - I imagine it was for your testing?

2024-04-12 00:39 UTC, wheregmis commented
Cleaned up 🎉

2024-04-12 01:52 UTC, DogeDark requested changes
One last thing. I tested it out and I had some problems with it displaying correctly with the ``align-items`` property. I removed them and all seems correct. Perhaps they should be removed?

2024-04-12 01:52 UTC, DogeDark commented on components/src/styles/column.scss
> +    align-items: center;
Here

2024-04-12 01:52 UTC, DogeDark commented on components/src/styles/row.scss
> +    align-items: center;
Here

2024-04-12 02:01 UTC, wheregmis commented
> One last thing. I tested it out and I had some problems with it displaying correctly with the `align-items` property. I removed them and all seems correct. Perhaps they should be removed?

Sure, its removed ✔️

2024-04-12 02:02 UTC, DogeDark commented
Awesome, this is great! Thanks for the addition!

2024-04-12 02:02 UTC, merged